# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Imitrainer' do
  pod 'Beethoven'
  pod 'FDWaveformView’
  pod ‘SoundWave’
  pod 'AudioKit'
  pod 'Cosmos', '~> 13.0'


  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Imitrainer

end
